# Default values for mifosx-mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: fintecheando/fineract:develop
  pullPolicy: IfNotPresent
  tag: "v1"

image:
  repository: fintecheando/fineract:develop
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: LoadBalancer
  port: 443